package MarksEnsias.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Etudiant = 0;
  public static final int ListEtudiant = 1;
  public static final int Module = 2;
  public static final int Programe = 3;
  public static final int Time = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x35be28bf56d643e3L, 0xbe30cde8df3542daL);
    builder.put(0x4cc498f6809f3417L, Etudiant);
    builder.put(0x4cc498f680a15f52L, ListEtudiant);
    builder.put(0x4cc498f6809f171aL, Module);
    builder.put(0x4cc498f6809f030fL, Programe);
    builder.put(0x4cc498f6809ed9faL, Time);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
