package MarksEnsias.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptEtudiant = createDescriptorForEtudiant();
  /*package*/ final ConceptDescriptor myConceptListEtudiant = createDescriptorForListEtudiant();
  /*package*/ final ConceptDescriptor myConceptModule = createDescriptorForModule();
  /*package*/ final ConceptDescriptor myConceptPrograme = createDescriptorForPrograme();
  /*package*/ final ConceptDescriptor myConceptTime = createDescriptorForTime();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptEtudiant, myConceptListEtudiant, myConceptModule, myConceptPrograme, myConceptTime);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Etudiant:
        return myConceptEtudiant;
      case LanguageConceptSwitch.ListEtudiant:
        return myConceptListEtudiant;
      case LanguageConceptSwitch.Module:
        return myConceptModule;
      case LanguageConceptSwitch.Programe:
        return myConceptPrograme;
      case LanguageConceptSwitch.Time:
        return myConceptTime;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForEtudiant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MarksEnsias", "Etudiant", 0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f3417L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:981eca2d-e61c-4e06-bcba-87205168fda0(MarksEnsias.structure)/5531714426805105687");
    b.version(3);
    b.property("note", 0x4cc498f6809f50c1L).type(PrimitiveTypeId.STRING).origin("5531714426805113025").done();
    b.property("status", 0x4cc498f6809f527dL).type(PrimitiveTypeId.STRING).origin("5531714426805113469").done();
    b.alias("information d'étudiant");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListEtudiant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MarksEnsias", "ListEtudiant", 0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f680a15f52L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:981eca2d-e61c-4e06-bcba-87205168fda0(MarksEnsias.structure)/5531714426805247826");
    b.version(3);
    b.aggregate("etudiants", 0x4cc498f680a169b1L).target(0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f3417L).optional(true).ordered(true).multiple(true).origin("5531714426805250481").done();
    b.alias("List des étudiants");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MarksEnsias", "Module", 0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f171aL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:981eca2d-e61c-4e06-bcba-87205168fda0(MarksEnsias.structure)/5531714426805098266");
    b.version(3);
    b.property("id", 0x4cc498f6809f258bL).type(PrimitiveTypeId.STRING).origin("5531714426805101963").done();
    b.associate("etudiants", 0x4cc498f680a3bc58L).target(0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f680a15f52L).optional(true).origin("5531714426805402712").done();
    b.aggregate("element", 0x4cc498f6809f34e8L).target(0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f171aL).optional(true).ordered(true).multiple(true).origin("5531714426805105896").done();
    b.alias("module du programe");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPrograme() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MarksEnsias", "Programe", 0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f030fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:981eca2d-e61c-4e06-bcba-87205168fda0(MarksEnsias.structure)/5531714426805093135");
    b.version(3);
    b.property("module", 0x4cc498f6809f0d54L).type(PrimitiveTypeId.STRING).origin("5531714426805095764").done();
    b.aggregate("elements", 0x4cc498f6809f2c75L).target(0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f171aL).optional(false).ordered(true).multiple(true).origin("5531714426805103733").done();
    b.alias("Programe d'une matiere");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTime() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MarksEnsias", "Time", 0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809ed9faL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:981eca2d-e61c-4e06-bcba-87205168fda0(MarksEnsias.structure)/5531714426805082618");
    b.version(3);
    b.property("annee_uni", 0x4cc498f6809ee6c9L).type(PrimitiveTypeId.STRING).origin("5531714426805085897").done();
    b.property("filier", 0x4cc498f6809eebc5L).type(PrimitiveTypeId.STRING).origin("5531714426805087173").done();
    b.property("semstre", 0x4cc498f6809eef8aL).type(PrimitiveTypeId.STRING).origin("5531714426805088138").done();
    b.property("periode", 0x4cc498f6809ef5f4L).type(PrimitiveTypeId.INTEGER).origin("5531714426805089780").done();
    b.aggregate("programe", 0x4cc498f6809f61d7L).target(0x35be28bf56d643e3L, 0xbe30cde8df3542daL, 0x4cc498f6809f030fL).optional(false).ordered(true).multiple(true).origin("5531714426805117399").done();
    b.alias("Periode Universitaire");
    return b.create();
  }
}
